language: node_js
node_js:
- '0.12'
- '0.11'

script:
  - "npm run build"
  - "set -e"
  - "npm run cull"
  - "npm test"

after_script:
  - "npm install -g istanbul"
  - "npm install -g codecov.io"
  - "istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./spec/spec.js"
  - "cat ./coverage/lcov.info | codecov"
