language: node_js
node_js:
- '0.12'
- '0.11'

before_install:
  - sudo pip install codecov

script:
  - "set -e"
  - "npm run cull"
  - "npm test"

after_success:
  - bash <(curl -s https://codecov.io/bash)
